name: 'FileToBase64'
description: 'Converts a file to a base64 string'
inputs:
  filePath:  # id of input
    description: 'filePath of a file to base64 encode'
    required: true
    default: ''
outputs:
  base64: # output will be available to future steps 
    description: 'Base64 encoded file'
runs:
  using: 'node12'
  main: 'dist/index.js'
